{{- $portName := include "syntheticapi.portName" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "syntheticapi.fullname" . }}
  labels:
    {{- include "syntheticapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ $portName }}
      protocol: TCP
      name: {{ $portName }}
  selector:
    {{- include "syntheticapi.selectorLabels" . | nindent 4 }}
